export type IconProps = {
  icon: Icons;
  size?: number;
};

export enum Icons {
  Home = "\uE80F",
  Processor = "\uEEA1",
  Storage = "\uEDA2",
  Settings = "\uE713",
  Motherboard = "\uE964",
  Memory = "\uEEA0",
  Graphics = "\uF211",
  Network = "\uE839",
  Refresh = "\uE72C",
  Design = "\uEB3C",
  Megaphone = "\uE789",
  Copy = "\uE8C8",
  Repair = "\uE90F",
  Color = "\uE790",
  Info = "\uE946",
  InfoFilled = "\uF167",
  Display = "\uE7F4",
  ChevronUp = "\uE70E",
  ChevronDown = "\uE70D",
  Sync = "\uEDAB",
  Usb = "\uECF0",
  Delete = "\uE74D",
  ErrorFilled = "\uEB90",
  Speaker = "\uE7F5",
  Language = "\uF2B7",

  // Search = "\uE721",
  // GiftBox = "\uF133",
  // Package = "\uE7B8",
  // Menu = "\uE712",
  // Add = "\uE710",
  // Folder = "\uE8B7",
  // AddFolder = "\uE8F4",
  // Audio = "\uE8D6",
  // Clock = "\uE121",
  // Playlist = "\uE93C",
  // Save = "\uE74E",
  // SaveLocal = "\uE78C",
  // Download = "\uE896",

  // Import = "\uE8B5",
  // Rename = "\uE8AC",
  // Certificate = "\uEB95",
  // Play = "\uE768",
  // ChevronUp = "\uE70E",
  // ChevronDown = "\uE70D",
  // CheckMark = "\uE73E",
  // Cancel = "\uE711",

  // Info = "\uE946",
  // Path = "\uE62F",
}
