export { Graphics } from "./graphics/Graphics";
export { Home } from "./home/Home";
export { Memory } from "./memory/Memory";
export { Motherboard } from "./motherboard/Motherboard";
export { Network } from "./network/Network";
export { Processor } from "./processor/Processor";
export { Settings } from "./settings/Settings";
export { Storage } from "./storage/Storage";
export { Usb } from "./usb/Usb";
