import type { Theme } from "@emotion/react";

export type ColorThemes = "light" | "dark";

type Themes = Record<ColorThemes, Theme>;

export const themes: Themes = {
  light: {
    // global
    background: "#f3f3f3",
    color: "#1a1a1a",
    focusOutline: "#1a1a1a",
    // selection
    selectionBackground: "#1a1a1a",
    selectionColor: "#f3f3f3",
    // scrollbar
    scrollBarThumbBackground: "#8a8a8a",
    scrollBarThumbHoverBackground: "#8a8a8a",
    // badge
    badgeBackground: "#fbfbfb",
    badgeBorder: "#e5e5e5",
    badgeColor: "#1a1a1a",
    // button
    buttonBackground: "#fbfbfb",
    buttonColor: "#1a1a1a",
    buttonBorder: "#e5e5e5",
    buttonDisabledBackground: "#f5f5f5",
    buttonDisabledColor: "#9b9b9b",
    buttonDisabledBorder: "#e5e5e5",
    buttonHoverBackground: "#f5f5f5",
    buttonHoverBorder: "#e5e5e5",
    buttonActiveBackground: "#f5f5f5",
    buttonActiveBorder: "#e5e5e5",
    buttonFocusOutline: "#1a1a1a",
    // comboBox
    comboBoxBackground: "#fbfbfb",
    comboBoxColor: "#1a1a1a",
    comboBoxBorder: "#e5e5e5",
    comboBoxDisabledBackground: "#f5f5f5",
    comboBoxDisabledColor: "#9b9b9b",
    comboBoxDisabledBorder: "#e5e5e5",
    comboBoxHoverBackground: "#f5f5f5",
    comboBoxHoverBorder: "#e5e5e5",
    comboBoxActiveBackground: "#f5f5f5",
    comboBoxActiveBorder: "#e5e5e5",
    comboBoxFocusOutline: "#1a1a1a",
    comboBoxMenuBackground: "#f9f9f9",
    comboBoxMenuBorder: "#e0e0e0",
    comboBoxMenuItemBackground: "#f9f9f9",
    comboBoxMenuItemColor: "#1a1a1a",
    comboBoxMenuItemHoverBackground: "#f0f0f0",
    comboBoxMenuItemActiveBackground: "#f0f0f0",
    // dataPanel
    dataPanelKeyColor: "#1a1a1a",
    dataPanelValueColor: "#5d5d5d",
    // infoBar
    infoBarErrorBackground: "#fde7e9",
    infoBarErrorColor: "#c42b1c",
    infoBarInfoBackground: "#fbfbfb",
    infoBarInfoColor: "#0078d4",
    infoBarWarningBackground: "#fff4ce",
    infoBarWarningColor: "#9d5d00",
    infoBarBorder: "#e5e5e5",
    infoBarColor: "#1a1a1a",
    infoBarDescriptionColor: "#5d5d5d",
    // label
    labelColor: "#5d5d5d",
    // nav
    navBorder: "#e5e5e5",
    navButtonColor: "#1a1a1a",
    navButtonBackground: "#f3f3f3",
    navButtonSelectedBackground: "#eaeaea",
    navButtonHoverBackground: "#eaeaea",
    navButtonActiveBackground: "#ededed",
    // page
    pageBorder: "#e5e5e5",
    // panel
    panelBackground: "#fbfbfb",
    panelBorder: "#e5e5e5",
    panelHeaderColor: "#1a1a1a",
    panelHeaderDescriptionColor: "#5d5d5d",
    panelChildrenBorder: "#e5e5e5",
  },
  dark: {
    // global
    background: "#282828",
    color: "#fff",
    focusOutline: "#fff",
    // selection
    selectionBackground: "#9D9D9D",
    selectionColor: "#282828",
    // scrollbar
    scrollBarThumbBackground: "#9D9D9D",
    scrollBarThumbHoverBackground: "#9D9D9D",
    // badge
    badgeBackground: "#353535",
    badgeBorder: "#373737",
    badgeColor: "#fff",
    // button
    buttonBackground: "#353535",
    buttonColor: "#fff",
    buttonBorder: "#373737",
    buttonDisabledBackground: "#313131",
    buttonDisabledColor: "#767676",
    buttonDisabledBorder: "#373737",
    buttonHoverBackground: "#3A3A3A",
    buttonHoverBorder: "#3C3C3C",
    buttonActiveBackground: "#2F2F2F",
    buttonActiveBorder: "#373737",
    buttonFocusOutline: "#fff",
    // comboBox
    comboBoxBackground: "#353535",
    comboBoxColor: "#fff",
    comboBoxBorder: "#373737",
    comboBoxDisabledBackground: "#313131",
    comboBoxDisabledColor: "#767676",
    comboBoxDisabledBorder: "#373737",
    comboBoxHoverBackground: "#3A3A3A",
    comboBoxHoverBorder: "#3C3C3C",
    comboBoxActiveBackground: "#2F2F2F",
    comboBoxActiveBorder: "#373737",
    comboBoxFocusOutline: "#fff",
    comboBoxMenuBackground: "#353535",
    comboBoxMenuBorder: "#373737",
    comboBoxMenuItemBackground: "#353535",
    comboBoxMenuItemColor: "#fff",
    comboBoxMenuItemHoverBackground: "#3A3A3A",
    comboBoxMenuItemActiveBackground: "#2F2F2F",
    // dataPanel
    dataPanelKeyColor: "#fff",
    dataPanelValueColor: "#cecece",
    // infoBar
    infoBarErrorBackground: "#442726",
    infoBarErrorColor: "#ff99a4",
    infoBarInfoBackground: "#272727",
    infoBarInfoColor: "#4CC2FF",
    infoBarWarningBackground: "#433519",
    infoBarWarningColor: "#FCE100",
    infoBarBorder: "#242424",
    infoBarColor: "#fff",
    infoBarDescriptionColor: "#cecece",
    // label
    labelColor: "#cecece",
    // nav
    navBorder: "#373737",
    navButtonColor: "#fff",
    navButtonBackground: "#282828",
    navButtonSelectedBackground: "#353535",
    navButtonHoverBackground: "#3A3A3A",
    navButtonActiveBackground: "#2F2F2F",
    // page
    pageBorder: "#373737",
    // panel
    panelBackground: "#2C2C2C",
    panelBorder: "#242424",
    panelHeaderColor: "#fff",
    panelHeaderDescriptionColor: "#cecece",
    panelChildrenBorder: "#242424",
  },
};
